config/routes.rb
Rails.application.routes.draw do
  get 'routing/show'

  resources :games
  resources :books
  get 'git_http/show'

  resources :widgets
  get 'models_need_dots/show'

  get 'taco_order/edit'

  get 'hello_angular/show'

end

app/models/book.rb
class Book < ActiveRecord::Base
end

app/models/game.rb
class Game < ActiveRecord::Base
end

app/models/widget.rb
class Widget < ActiveRecord::Base
	validates :price, presence: true, numericality: { greater_than: 10}
	validates :name, presence: true, length: {minimum: 7}

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]

  # GET /books
  # GET /books.json
  def index
    @books = Book.all

    respond_to do |format|
        format.html {
          @books_json = @books.map{|b| BookSerializer.new(b).serializable_hash }
          @urls = {
            books: books_path 
          }
        } 
        format.json {render json: @books}
    end
  end

  # GET /books/1
  # GET /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books
  # POST /books.json
  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Book was successfully created.' }
        format.json { render json: @book }
      else
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { render json: @book}
      else
        format.html { render :edit }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: 'Book was successfully destroyed.' }
      format.json {  render json: {message: "Book was deleted"} }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_params
      params.require(:book).permit(:title, :author)
    end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game, only: [:show, :edit, :update, :destroy]

  # GET /games
  # GET /games.json
  def index
    @games = Game.page( params[:page]).per(10 )

    respond_to do |format|
      format.html {}
      format.json { render json: @games, meta: {
          number_of_pages: @games.num_pages,
          current_page: @games.current_page, 
          total_count: @games.total_count

        } 
      }
    end
  end

  # GET /games/1
  # GET /games/1.json
  def show
  end

  # GET /games/new
  def new
    @game = Game.new
  end

  # GET /games/1/edit
  def edit
  end

  # POST /games
  # POST /games.json
  def create
    @game = Game.new(game_params)

    respond_to do |format|
      if @game.save
        format.html { redirect_to @game, notice: 'Game was successfully created.' }
        format.json { render :show, status: :created, location: @game }
      else
        format.html { render :new }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /games/1
  # PATCH/PUT /games/1.json
  def update
    respond_to do |format|
      if @game.update(game_params)
        format.html { redirect_to @game, notice: 'Game was successfully updated.' }
        format.json { render :show, status: :ok, location: @game }
      else
        format.html { render :edit }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /games/1
  # DELETE /games/1.json
  def destroy
    @game.destroy
    respond_to do |format|
      format.html { redirect_to games_url, notice: 'Game was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_game
      @game = Game.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def game_params
      params.require(:game).permit(:name)
    end
end

app/controllers/git_http_controller.rb
class GitHttpController < ApplicationController
  def show
  end
end

app/controllers/hello_angular_controller.rb
class HelloAngularController < ApplicationController
  def show
  end
end

app/controllers/models_need_dots_controller.rb
class ModelsNeedDotsController < ApplicationController
  def show
  end
end

app/controllers/routing_controller.rb
class RoutingController < ApplicationController
  def show
  end
end

app/controllers/taco_order_controller.rb
class TacoOrderController < ApplicationController
  def edit
  end
end

app/controllers/widgets_controller.rb
class WidgetsController < ApplicationController
  before_action :set_widget, only: [:show, :edit, :update, :destroy]

  # GET /widgets
  # GET /widgets.json
  def index
    @widgets = Widget.all
  end

  # GET /widgets/1
  # GET /widgets/1.json
  def show
  end

  # GET /widgets/new
  def new
    @widget = Widget.new
  end

  # GET /widgets/1/edit
  def edit
  end

  # POST /widgets
  # POST /widgets.json
  def create
    @widget = Widget.new(widget_params)

    respond_to do |format|
      if @widget.save
        format.html { redirect_to @widget, notice: 'Widget was successfully created.' }
        format.json { render :show, status: :created, location: @widget }
      else
        format.html { render :new }
        format.json { render json: @widget.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /widgets/1
  # PATCH/PUT /widgets/1.json
  def update
    respond_to do |format|
      if @widget.update(widget_params)
        format.html { redirect_to @widget, notice: 'Widget was successfully updated.' }
        format.json { render :show, status: :ok, location: @widget }
      else
        format.html { render :edit }
        format.json { render json: @widget.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /widgets/1
  # DELETE /widgets/1.json
  def destroy
    @widget.destroy
    respond_to do |format|
      format.html { redirect_to widgets_url, notice: 'Widget was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_widget
      @widget = Widget.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def widget_params
      params.require(:widget).permit(:name, :price)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/git_http_helper.rb
module GitHttpHelper
end

app/helpers/hello_angular_helper.rb
module HelloAngularHelper
end

app/helpers/models_need_dots_helper.rb
module ModelsNeedDotsHelper
end

app/helpers/routing_helper.rb
module RoutingHelper
end

app/helpers/taco_order_helper.rb
module TacoOrderHelper
end

app/helpers/widgets_helper.rb
module WidgetsHelper
end

app/views/books/_form.html.erb
<%= form_for(@book) do |f| %>
  <% if @book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :author %><br>
    <%= f.text_field :author %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/books/edit.html.erb
<h1>Editing Book</h1>

<%= render 'form' %>

<%= link_to 'Show', @book %> |
<%= link_to 'Back', books_path %>

app/views/books/index.html.erb
<div ng-app="AngulaRails" ng-controller="BooksController" 
      ng-init="urls=<%= @urls.to_json %>; books=<%= @books_json.to_json%> ">
  <div class="row">

    <div class="col-md-6">
      <form ng-submit="save()">
        <div class="form-group">
          <label>Title</label>
          <input type="text" class="form-control" ng-model="book.title" />
        </div>

        <div class="form-group">
          <label>Author</label>
          <input type="text" class="form-control" ng-model="book.author" />
        </div>

        <button class="btn btn-primary">
          Save
        </button>
      </form>
    </div>



    <div class="col-md-6">
      <h1>Books</h1>
      <ul>
        <li ng-repeat="book in books">
          <div class="btn btn-defaut" ng-click="edit(book)">
            <i class="icon-pencil" />
          </div>
          <div class="btn btn-defaut" ng-click="delete(book)">
            <i class="icon-trash" />
          </div>
          {{ book.title }} by {{ book.author }}
        </li>
      </ul>
    </div>
  </div>
</div>

app/views/books/new.html.erb
<h1>New Book</h1>

<%= render 'form' %>

<%= link_to 'Back', books_path %>

app/views/books/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @book.title %>
</p>

<p>
  <strong>Author:</strong>
  <%= @book.author %>
</p>

<%= link_to 'Edit', edit_book_path(@book) %> |
<%= link_to 'Back', books_path %>

app/views/games/_form.html.erb
<%= form_for(@game) do |f| %>
  <% if @game.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@game.errors.count, "error") %> prohibited this game from being saved:</h2>

      <ul>
      <% @game.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/games/edit.html.erb
<h1>Editing Game</h1>

<%= render 'form' %>

<%= link_to 'Show', @game %> |
<%= link_to 'Back', games_path %>

app/views/games/index.html.erb
<div ng-app="AngulaRails" ng-controller="GamesController" ng-init="init()">
  <h1>Games</h1>

  <%= link_to "New Game", new_game_path, class: "btn btn-default" %>

  <br />
  <div ar-paging="paging" ar-current-page="currentPage" ar-paging-change="getGames"></div>
 

  <table class="table">
    <thead>
      <tr>
        <th>Name</th>
      </tr>
    </thead>

    <tbody>
      <tr ng-repeat="game in games">
        <td> {{ game.name }}</td>
      </tr>
    </tbody>
  </table>

</div>

app/views/games/new.html.erb
<h1>New Game</h1>

<%= render 'form' %>

<%= link_to 'Back', games_path %>

app/views/games/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @game.name %>
</p>

<%= link_to 'Edit', edit_game_path(@game) %> |
<%= link_to 'Back', games_path %>

app/views/git_http/show.html.erb
<div class="row" ng-app="AngulaRails" ng-controller="GitHttpController">
	<div class="col-md-6">
		<h1>Git $http</h1>
		<form ng-submit="search()">
			<div class="input-group">
				<span class="input-group-addon">
					<i class="icon-search"></i>
				</span>

				<input type='text' class="form-control" placeholder="Git Username"
					ng-model="username">
			</div>
		</form>


		<hr />
		<div class="alert alert-danger" ng-show="errorMessage">
			<strong><i class="icon-warning-sign"></i> Error! </strong>
			{{ errorMessage }}
		</div>
		<i class="icon-refresh icon-spin" ng-show="searching"></i>
		<ul class="list-group">
			<li class="list-group-item" ng-repeat="repo in repos">
				<h4 class="list-group-item-heading">{{ repo.full_name }}</h4>
				<p class="list-group-item-text text-muted">{{ repo.url }}</h4>
			</li>
		</ul>
	</div>
</div>

app/views/hello_angular/show.html.erb
<div class="row" ng-app="AngulaRails" ng-controller="HelloWorldController">
	<div class="col-md-6">
		<h1>Hello AngularJS</h1>
		<p>
			Type in the input box and watch as AngularJS update the 
			property through the magic of binding

			<b>{{awesome}}</b>
		</p>

		<input type="text" class="form-control" ng-model="myText" >
		{{myText}}
	</div>
</div>

app/views/models_need_dots/show.html.erb
<div ng-app="AngulaRails" ng-controller="ModelsNeedDotsController">
	<div class="row">
		<div class="col-md-12">
			<h1>Oh noes!</h1>
			Message is "{{someModel.message}}"
			<input type="text" class="form-control" ng-model="someModel.message" />

			<ul class="list-unstyled">
				<li ng-repeat="s in stuff" style="margin-top:10px">
					Message is "{{ someModel.message }}"

					<input type="text" class="form-control" ng-model="someModel.message" />
				</li>
			</ul>
		</div>
	</div>
</div>

app/views/routing/show.html.erb
<div class="row" ng-app="AngulaRails">
	<div class="col-md-12">
		<h1>Routing Example</h1>
		<div ng-view></div>
	</div>
</div>

app/views/taco_order/edit.html.erb
<div class="row" ng-app="AngulaRails" ng-controller="TacoOrderController">
	<div class="col-md-6">


		<h3>Add Taco to Order</h3>

		<form ng-submit="addTaco()">
			<div class="form-group">
				<label for="name">Name</label>
				<input type='text' class="form-control" 
				placeholder="Super Tasy"
				ng-model="taco.name" >
				</input> 
			</div>

			<div class="form-group">
				<label for="filling">Select your filling</label>
				<select ng-model="taco.filling" class="form-control"

					ng-options="f  for f in fillings">
		 			<option value="">Pick a Filling</option>

				</select>
			</div>

			<div class="form-group">
				<label>Extras</label>


				<div class="checkbox" ng-repeat="extra in extras">
					<label>
						<input type='checkbox' ng-model="extra.checked">
						</input>
						{{ extra.name }}
					</label>

				</div>
			</div>

			<div class="form-group">
				<label>Cheese</label>


				<div class="radio" ng-repeat="cheese in cheeses">
					<label>
						<input type='radio' value="{{cheese}}"
							ng-model="taco.cheese">
						</input>
						{{cheese}}
					</label> 
				</div>
 
			</div>
 



			<button class="btn btn-primary">
				Submit
			</button>
		</form>
	</div>

	<div class="col-md-6">
		<h3>Your Order</h3>

		<table class="table">
			<tbody>
				<tr ng-repeat="taco in tacos">
					<td>{{taco.name}}</td>
					<td>{{taco.filling}}</td>

					<td>
						<span ng-repeat="extra in taco.extras">
							{{ extra }}
						</span>
					</td>

					<td>{{taco.cheese}}</td>


				</tr>
			</tbody>
		</table>
	</div>
</div>

app/views/widgets/_form.html.erb
<div ng-app="AngulaRails">

  <%= form_for @widget, id: "widgetForm", html: {name: "widgetForm", "novalidate" => true}   do |f| %>
    <% if @widget.errors.any? %>
      <div class="alert alert-danger">
        <h4><%= pluralize(@widget.errors.count, "error") %></h4> 

        <ul>
          <% @widget.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %> 
        </ul>
      </div>
      
    <% end %>

    <div class="form-group" ng-class="{ 'has-error': widgetForm['widget[name]'].$invalid }">
      <%= f.label :name %><br>
      <%= f.text_field :name, :class => "form-control", "ng-model" => "name", required: true %>
      <span class="help-block" ng-show="widgetForm['widget[name]'].$error.required">Required</span>
    </div>
    <div class="form-group" ng-class="{ 'has-error': widgetForm['widget[price]'].$invalid}">
      <%= f.label :price %><br>
      <%= f.number_field :price , class: "form-control", "ng-model" => "price", required: true, "min" => "10" %>
      <span class="help-block" ng-show="widgetForm['widget[price]'].$error.required">a number is required</span>
      <span class="help-block" ng-show="widgetForm['widget[price]'].$error.min">Must be greater than 10</span>
    </div> 
    <%= f.submit "Save", class: "btn btn-primary", "ng-disabled" => "widgetForm.$invalid" %> 
  <% end %>

</div>

app/views/widgets/edit.html.erb
<h1>Editing Widget</h1>

<%= render 'form' %>

<%= link_to 'Show', @widget %> |
<%= link_to 'Back', widgets_path %>

app/views/widgets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Widgets</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @widgets.each do |widget| %>
      <tr>
        <td><%= widget.name %></td>
        <td><%= widget.price %></td>
        <td><%= link_to 'Show', widget %></td>
        <td><%= link_to 'Edit', edit_widget_path(widget) %></td>
        <td><%= link_to 'Destroy', widget, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Widget', new_widget_path %>

app/views/widgets/new.html.erb
<h1>New Widget</h1>

<%= render 'form' %>

<%= link_to 'Back', widgets_path %>

app/views/widgets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @widget.name %>
</p>

<p>
  <strong>Price:</strong>
  <%= @widget.price %>
</p>

<%= link_to 'Edit', edit_widget_path(@widget) %> |
<%= link_to 'Back', widgets_path %>